services:
  gateway-service:
    build: ./gateway-service
    ports:
      - "3000:3000"
    env_file:
      - ./gateway-service/.env
    depends_on:
      - auth-service
      - ip-service

  auth-service:
    build: ./auth-service
    env_file:
      - ./auth-service/.env
    expose:
      - "8001:8001"
    depends_on:
      - auth-db

  auth-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth_db
    volumes:
      - auth-db-data:/var/lib/mysql

  ip-service:
    build: ./ip-service
    env_file:
      - ./ip-service/.env
    expose:
      - "8002:8002"
    depends_on:
      - ip-db

  ip-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ip_db
    volumes:
      - ip-db-data:/var/lib/mysql

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - gateway-service

volumes:
  auth-db-data:
  ip-db-data: